site_name: PHPUnit-Expect
site_description: BDD assertion library based on PHPUnit, inspired by Chai.
site_author: Cédric Belin - cedric@belin.io
site_url: https://docs.belin.io/phpunit-expect

docs_dir: ../doc
site_dir: ../www

repo_name: git.belin.io
repo_url: https://git.belin.io/cedx/phpunit-expect
edit_uri: ''

copyright: Copyright &copy; 2017 - 2020 Cédric Belin
extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://belin.io'
    - icon: fontawesome/brands/github
      link: 'https://github.com/cedx'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/cedxbelin'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/cedxbelin'

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage:
      - Functions: usage/functions.md
      - Language chains: usage/chains.md
      - Flags: usage/flags.md
      - Assertions: usage/assertions.md
  - About:
      - License: about/license.md
      - See also: about/see_also.md

theme:
  favicon: img/favicon.ico
  features:
    - instant
  icon:
    logo: fontawesome/solid/book-reader
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    accent: purple
    primary: purple
