<?php
declare(strict_types=1);
namespace PHPUnit\Expect;

/**
 * Provides helper methods for BDD assertions.
 */
trait ExpectTrait {

  /**
   * Creates a new assertion.
   * @param mixed $target The target of the assertion.
   * @param string $message Message identifying the error generated by the assertion when it fails.
   * @return Assertion The newly created assertion.
   */
  public function expect($target, string $message = ''): Assertion {
    return new Assertion($target, $message);
  }

  /**
   * Provides the specification of a test block.
   * @param string $specification A message describing the test specification.
   * @param callable $block The test block to be invoked.
   */
  public function it(string $specification, callable $block) {
    call_user_func($block, $specification);
  }

  /**
   * Skips a test block.
   * @param string $specification A message describing the test specification.
   * @param callable $block The test block to be invoked.
   */
  public function skip(string $specification, callable $block) {
    // The test block is ignored.
  }
}
